services:
  redis_whypk:
    image: redis:latest
    container_name: redis_whypk
    restart: unless-stopped
    env_file:
      - .env
    command: /bin/bash -c "redis-server --save 20 1 --loglevel warning --requirepass $$REDIS_PASS"
    ports:
      - 6379:6379
    expose:
      - 6379:80
    cap_add:
      - SYS_NICE
    networks:
      - backend-networks
    environment:
      - REDIS_PASSWORD=password123
    volumes:
      - redis-data:/var/lib/redis
