services:
  api_producer:
    image: producerapi
    container_name: api_producer
    restart: unless-stopped
    depends_on:
      - pg
      - redis_whypk
      - kafka
    links:
      - pg
      - redis_whypk
      - kafka
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - backend-networks
    environment:
      DATABASE_URL: postgresql://whypark:whypark123@pg:5432/db_why_park?schema=public
      REDIS_PASS: password123
      REDIS_URI: redis://default:${REDIS_PASS}@redis_whypk:6379
      KAFKA_URL: kafka:9094
      ENVIRONMENT: dev
      JWT_ACCESS_SECRET: t323t24hgwafa=
      JWT_REFRESH_SECRET: asfqi33fgtrfewf3
      PORT: 3000
