// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api_consumer.Api.Reserva.Repository;

#nullable disable

namespace api_consumer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api_consumer.Api.Reserva.Entity.AvaliacaoEntity", b =>
                {
                    b.Property<int>("id_avaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_avaliacao"));

                    b.Property<string>("avaliacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("comentario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_cliente")
                        .HasColumnType("integer");

                    b.Property<int>("id_estacionamento")
                        .HasColumnType("integer");

                    b.HasKey("id_avaliacao");

                    b.ToTable("avaliacao");
                });

            modelBuilder.Entity("api_consumer.Api.Reserva.Entity.ReservaEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("canceledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("duracao")
                        .HasColumnType("integer");

                    b.Property<DateTime>("horario_reserva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("id_cliente")
                        .HasColumnType("integer");

                    b.Property<int>("id_estacionamento")
                        .HasColumnType("integer");

                    b.Property<int>("id_veiculo")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("reserva");
                });
#pragma warning restore 612, 618
        }
    }
}
