version: '3.8'
services:
  pg:
    image: postgres:12
    container_name: pg
    env_file:
      - .env
    ports:
      - 5432:5432
    expose:
      - 5432:80
    cap_add:
      - SYS_NICE
    networks:
      - backend-networks
    volumes:
      - postgres-db-data:/var/lib/postgres
